name: mervynlim
favicon: null
layout_spectrum: 0.74602
typography_spectrum: 0.65726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363233'
    - '#e4e4e2'
    - '#fcad71'
    - '#a66663'
    - '#fdea5e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
