title: Mervyn Lim
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6875
  brandStrength: 0.1875
  rhythmicContrast: 0.5
  brandColors:
    - '#363233'
    - '#e4e4e2'
    - '#fcad71'
    - '#a66663'
    - '#fdea5e'
  lightness: 0.5625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: mervynlim
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.65726
layout_spectrum: 0.3021277
