name: mervynlim
favicon: null
layout_spectrum: 0.3021277
typography_spectrum: 0.65726
title: Mervyn Lim
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363233'
    - '#e4e4e2'
    - '#fcad71'
    - '#a66663'
    - '#fcee35'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
