name: mervynlim
favicon: null
layout_spectrum: 0.27805
typography_spectrum: 0.6671
title: Mervyn Lim
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#EAAC87'
    - '#5CA4B3'
    - '#FBF3F2'
    - '#AC885B'
    - '#2F2720'
  brandStrength: 0.1468085
  lightness: 0.687234
  saturation: 0.6875
  rhythmicContrast: 0.3829787
purpose: []
